#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Global post-processing for Lambert J20 DBM-kernel sensitivity.

Purpose
-------
Compare, in the same figures:
    - Experimental data
    - Fluent/Lambert reference data
    - OpenFOAM kernel cases: PCM, Dinj/6, Dinj/3, Dinj, 3Dinj, 6Dinj

Expected folder structure
-------------------------
Run this script from:
    ~/runs/subsonic/Lambert_case_J20_kernelStudy

or place it in:
    ~/runs/subsonic/Lambert_case_J20_kernelStudy/postProcessing_kernelComparison/

Expected input profiles, already generated by the single-case post-processing:
    b_Dinj/postProcessing_Lambert_OpenFOAM/profile_OpenFOAM_30d.csv
    b_Dinj/postProcessing_Lambert_OpenFOAM/profile_OpenFOAM_60d.csv
    ... same for all kernel cases

Reference data
--------------
This script tries to import the reference datasets from the single-case
script, if it is available in the same folder:
    postProcessing_kernelComparison/postprocess_lambert_openfoam.py

The preferred format is a dictionary named REF:
    REF["30d"]["fluent_smd"] -> numpy array with columns [y_mm, D32_um]
    REF["30d"]["exp_smd"]    -> numpy array with columns [y_mm, D32_um]
    REF["30d"]["fluent_ux"]  -> numpy array with columns [y_mm, Ux_mps]
    REF["30d"]["exp_ux"]     -> numpy array with columns [y_mm, Ux_mps]

and same for "60d".

If REF is not found, the script still plots the OpenFOAM kernel cases and writes
a warning. In that case, add/copy the old single-case script next to this file.
"""

from __future__ import annotations

import argparse
import importlib.util
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------------
# Default configuration
# ---------------------------------------------------------------------------
DEFAULT_CASES = {
    # Disabled from comparison plots (uncomment to re-enable):
    # "b_0_PCM": {
    #     "label": r"PCM, b = 0, cellPoint",
    #     "b_over_Dinj": 0.0,
    #     "smoothBandwidth_m": 0.0,
    # },
    "b_0_PCM_cell": {
        "label": r"PCM, b = 0",
        "b_over_Dinj": 0.0,
        "smoothBandwidth_m": 0.0,
    },
    # "b_Dinj_over6": {
    #     "label": r"DBM, b = $D_{inj}/6$",
    #     "b_over_Dinj": 1.0 / 6.0,
    #     "smoothBandwidth_m": 0.0000761666667,
    # },
    # "b_Dinj_over3": {
    #     "label": r"DBM, b = $D_{inj}/3$",
    #     "b_over_Dinj": 1.0 / 3.0,
    #     "smoothBandwidth_m": 0.0001523333333,
    # },
    "b_Dinj": {
        "label": r"DBM, b = $D_{inj}$",
        "b_over_Dinj": 1.0,
        "smoothBandwidth_m": 0.000457,
    },
    # "b_2Dinj": {
    #     "label": r"DBM, b = $2D_{inj}$",
    #     "b_over_Dinj": 2.0,
    #     "smoothBandwidth_m": 0.000914,
    # },
    "b_3Dinj": {
        "label": r"DBM, b = $3D_{inj}$",
        "b_over_Dinj": 3.0,
        "smoothBandwidth_m": 0.001371,
    },
    "b_6Dinj": {
        "label": r"DBM, b = $6D_{inj}$",
        "b_over_Dinj": 6.0,
        "smoothBandwidth_m": 0.002742,
    },
}

PLANES = ["30d", "60d"]
QUANTITIES = {
    "D32_um": {
        "xlabel": r"$D_{32}$ [$\mu$m]",
        "title_name": r"$D_{32}$",
        "xlim": (0.0, 50.0),
        "ref_fluent": "fluent_smd",
        "ref_exp": "exp_smd",
    },
    "Ux_mean": {
        "xlabel": r"$U_x$ [m/s]",
        "title_name": r"$U_x$",
        "xlim": (0.0, 160.0),
        "ref_fluent": "fluent_ux",
        "ref_exp": "exp_ux",
    },
}

YLIMS = {
    "30d": (0.0, 15.0),
    "60d": (0.0, 16.0),
}


# ---------------------------------------------------------------------------
# Path handling
# ---------------------------------------------------------------------------
def infer_paths(script_path: Path, root_arg: Optional[str]) -> Tuple[Path, Path]:
    """Return (root_case_dir, output_dir)."""
    if root_arg is not None:
        root = Path(root_arg).expanduser().resolve()
        out_dir = root / "postProcessing_kernelComparison"
    else:
        if script_path.parent.name == "postProcessing_kernelComparison":
            out_dir = script_path.parent
            root = out_dir.parent
        else:
            root = Path.cwd().resolve()
            out_dir = root / "postProcessing_kernelComparison"

    out_dir.mkdir(parents=True, exist_ok=True)
    return root, out_dir


# ---------------------------------------------------------------------------
# Reference data import
# ---------------------------------------------------------------------------
def _load_module_from_file(py_file: Path) -> Optional[Any]:
    if not py_file.exists():
        return None

    spec = importlib.util.spec_from_file_location(py_file.stem, py_file)
    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)  # type: ignore[attr-defined]
    except SystemExit:
        return None
    except Exception as exc:
        print(f"WARNING: could not import {py_file}: {exc}")
        return None
    return module


def _as_array(obj: Any) -> Optional[np.ndarray]:
    try:
        arr = np.asarray(obj, dtype=float)
    except Exception:
        return None

    if arr.ndim != 2 or arr.shape[1] < 2 or arr.shape[0] < 1:
        return None
    return arr[:, :2]


def normalize_ref_dict(raw_ref: Any) -> Dict[str, Dict[str, np.ndarray]]:
    """Normalize possible REF-like structures to REF[plane][key] arrays."""
    ref: Dict[str, Dict[str, np.ndarray]] = {"30d": {}, "60d": {}}

    if not isinstance(raw_ref, dict):
        return ref

    for plane in PLANES:
        if plane in raw_ref and isinstance(raw_ref[plane], dict):
            for key in ["fluent_smd", "exp_smd", "fluent_ux", "exp_ux"]:
                arr = _as_array(raw_ref[plane].get(key))
                if arr is not None:
                    ref[plane][key] = arr

    return ref


def discover_ref_from_module(module: Any) -> Dict[str, Dict[str, np.ndarray]]:
    """Try to discover reference arrays from a previous script."""
    if hasattr(module, "REF"):
        ref = normalize_ref_dict(getattr(module, "REF"))
        if any(ref[p] for p in PLANES):
            return ref

    ref: Dict[str, Dict[str, np.ndarray]] = {"30d": {}, "60d": {}}
    candidates = vars(module)

    synonyms = {
        ("30d", "fluent_smd"): ["fluent_smd_30d", "fluent_d32_30d", "lambert_smd_30d", "lambert_d32_30d"],
        ("60d", "fluent_smd"): ["fluent_smd_60d", "fluent_d32_60d", "lambert_smd_60d", "lambert_d32_60d"],
        ("30d", "exp_smd"): ["exp_smd_30d", "exp_d32_30d", "experimental_smd_30d", "experimental_d32_30d"],
        ("60d", "exp_smd"): ["exp_smd_60d", "exp_d32_60d", "experimental_smd_60d", "experimental_d32_60d"],
        ("30d", "fluent_ux"): ["fluent_ux_30d", "lambert_ux_30d"],
        ("60d", "fluent_ux"): ["fluent_ux_60d", "lambert_ux_60d"],
        ("30d", "exp_ux"): ["exp_ux_30d", "experimental_ux_30d"],
        ("60d", "exp_ux"): ["exp_ux_60d", "experimental_ux_60d"],
    }

    lower_map = {name.lower(): name for name in candidates.keys()}
    for (plane, key), names in synonyms.items():
        for name in names:
            actual = lower_map.get(name.lower())
            if actual is None:
                continue
            arr = _as_array(candidates[actual])
            if arr is not None:
                ref[plane][key] = arr
                break

    return ref


def load_reference_data(out_dir: Path, explicit_script: Optional[str]) -> Dict[str, Dict[str, np.ndarray]]:
    """Load reference data from the single-case postprocessing script."""
    search_files = []
    if explicit_script:
        search_files.append(Path(explicit_script).expanduser())
    search_files.append(out_dir / "postprocess_lambert_openfoam.py")

    for py_file in search_files:
        module = _load_module_from_file(py_file)
        if module is None:
            continue
        ref = discover_ref_from_module(module)
        if any(ref[p] for p in PLANES):
            print(f"Reference data loaded from: {py_file}")
            return ref

    print("WARNING: no reference data found. Kernel curves will be plotted without Fluent/experimental data.")
    print("         Put postprocess_lambert_openfoam.py next to this script and ensure it exposes REF.")
    return {"30d": {}, "60d": {}}


# ---------------------------------------------------------------------------
# Single-case postprocessing execution, optional
# ---------------------------------------------------------------------------
def run_single_postprocessing(root: Path, out_dir: Path, cases: Iterable[str], args: argparse.Namespace) -> None:
    script = out_dir / "postprocess_lambert_openfoam.py"
    if not script.exists():
        raise FileNotFoundError(
            f"Cannot run single-case postprocessing because this file is missing: {script}"
        )

    for case in cases:
        case_dir = root / case
        if not case_dir.exists():
            print(f"WARNING: skipping missing case {case_dir}")
            continue

        cmd = [
            sys.executable,
            str(script),
            "--case",
            str(case_dir),
            "--dz",
            str(args.dz),
            "--min-events",
            str(args.min_events),
            "--bins",
            str(args.bins),
            "--y-min",
            str(args.y_min),
            "--y-max",
            str(args.y_max),
        ]
        print("Running:", " ".join(cmd))
        subprocess.run(cmd, check=True)


# ---------------------------------------------------------------------------
# Profile loading and metrics
# ---------------------------------------------------------------------------
def load_profile(root: Path, case: str, plane: str) -> pd.DataFrame:
    f = root / case / "postProcessing_Lambert_OpenFOAM" / f"profile_OpenFOAM_{plane}.csv"
    if not f.exists():
        print(f"WARNING: missing profile: {f}")
        return pd.DataFrame()
    try:
        return pd.read_csv(f)
    except Exception as exc:
        print(f"WARNING: could not read {f}: {exc}")
        return pd.DataFrame()


def finite_xy(df: pd.DataFrame, quantity: str) -> Tuple[np.ndarray, np.ndarray]:
    if df.empty or "y_center_mm" not in df.columns or quantity not in df.columns:
        return np.array([]), np.array([])

    x = df[quantity].to_numpy(dtype=float)
    y = df["y_center_mm"].to_numpy(dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)

    if ok.sum() == 0:
        return np.array([]), np.array([])

    order = np.argsort(y[ok])
    return x[ok][order], y[ok][order]


def rmse_against_ref(df: pd.DataFrame, quantity: str, ref_arr: Optional[np.ndarray]) -> float:
    if ref_arr is None or ref_arr.size == 0:
        return np.nan

    x, y = finite_xy(df, quantity)
    if len(x) < 2:
        return np.nan

    y_ref = ref_arr[:, 0].astype(float)
    x_ref = ref_arr[:, 1].astype(float)
    inside = (y_ref >= y.min()) & (y_ref <= y.max()) & np.isfinite(y_ref) & np.isfinite(x_ref)
    if inside.sum() < 2:
        return np.nan

    x_interp = np.interp(y_ref[inside], y, x)
    return float(np.sqrt(np.mean((x_interp - x_ref[inside]) ** 2)))


def nanmean_col(df: pd.DataFrame, col: str) -> float:
    if df.empty or col not in df.columns:
        return np.nan
    arr = df[col].to_numpy(dtype=float)
    return float(np.nanmean(arr)) if np.isfinite(arr).any() else np.nan


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------
def plot_panel(
    ax: Any,
    root: Path,
    cases: Dict[str, Dict[str, Any]],
    ref: Dict[str, Dict[str, np.ndarray]],
    plane: str,
    quantity: str,
    include_refs: bool = True,
) -> None:
    qconf = QUANTITIES[quantity]

    if include_refs:
        fluent = ref.get(plane, {}).get(qconf["ref_fluent"])
        exp = ref.get(plane, {}).get(qconf["ref_exp"])

        if fluent is not None:
            ax.plot(fluent[:, 1], fluent[:, 0], "-", linewidth=2.2, label="Fluent / Lambert")
        if exp is not None:
            ax.plot(exp[:, 1], exp[:, 0], "s", markersize=5, label="Experiment")

    for case, meta in cases.items():
        df = load_profile(root, case, plane)
        x, y = finite_xy(df, quantity)
        if len(x) == 0:
            continue
        ax.plot(x, y, "-", linewidth=1.6, label=meta["label"])

    ax.set_xlabel(qconf["xlabel"])
    ax.set_ylabel("y [mm]")
    ax.set_title(f"{qconf['title_name']} at x/d = {plane.replace('d', '')}")
    ax.set_xlim(*qconf["xlim"])
    ax.set_ylim(*YLIMS[plane])
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)


def make_combined_figure(root: Path, out_dir: Path, cases: Dict[str, Dict[str, Any]], ref: Dict[str, Dict[str, np.ndarray]]) -> None:
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    plot_panel(axs[0, 0], root, cases, ref, "30d", "D32_um")
    plot_panel(axs[0, 1], root, cases, ref, "60d", "D32_um")
    plot_panel(axs[1, 0], root, cases, ref, "30d", "Ux_mean")
    plot_panel(axs[1, 1], root, cases, ref, "60d", "Ux_mean")

    fig.suptitle("Lambert J20 — DBM kernel sensitivity", y=1.01, fontsize=14)
    fig.tight_layout()
    out = out_dir / "Lambert_J20_kernel_comparison_all.png"
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out}")


def make_quantity_figures(root: Path, out_dir: Path, cases: Dict[str, Dict[str, Any]], ref: Dict[str, Dict[str, np.ndarray]]) -> None:
    for quantity, filename in [
        ("D32_um", "Lambert_J20_kernel_comparison_D32.png"),
        ("Ux_mean", "Lambert_J20_kernel_comparison_Ux.png"),
    ]:
        fig, axs = plt.subplots(1, 2, figsize=(12, 5))
        plot_panel(axs[0], root, cases, ref, "30d", quantity)
        plot_panel(axs[1], root, cases, ref, "60d", quantity)
        fig.tight_layout()
        out = out_dir / filename
        fig.savefig(out, dpi=300, bbox_inches="tight")
        plt.close(fig)
        print(f"Saved: {out}")


def make_single_plane_figures(root: Path, out_dir: Path, cases: Dict[str, Dict[str, Any]], ref: Dict[str, Dict[str, np.ndarray]]) -> None:
    for plane in PLANES:
        for quantity, suffix in [("D32_um", "D32"), ("Ux_mean", "Ux")]:
            fig, ax = plt.subplots(figsize=(7, 6))
            plot_panel(ax, root, cases, ref, plane, quantity)
            fig.tight_layout()
            out = out_dir / f"Lambert_J20_kernel_comparison_{suffix}_{plane}.png"
            fig.savefig(out, dpi=300, bbox_inches="tight")
            plt.close(fig)
            print(f"Saved: {out}")


# ---------------------------------------------------------------------------
# Summary CSV
# ---------------------------------------------------------------------------
def write_summary(root: Path, out_dir: Path, cases: Dict[str, Dict[str, Any]], ref: Dict[str, Dict[str, np.ndarray]]) -> None:
    rows = []

    for case, meta in cases.items():
        row: Dict[str, Any] = {
            "case": case,
            "label": meta["label"],
            "b_over_Dinj": meta["b_over_Dinj"],
            "smoothBandwidth_m": meta["smoothBandwidth_m"],
        }

        for plane in PLANES:
            df = load_profile(root, case, plane)
            row[f"valid_bins_{plane}"] = int(np.isfinite(df["D32_um"]).sum()) if not df.empty and "D32_um" in df else 0
            row[f"D32_mean_um_{plane}"] = nanmean_col(df, "D32_um")
            row[f"Ux_mean_mps_{plane}"] = nanmean_col(df, "Ux_mean")

            for user in [0, 1, 2]:
                row[f"mean_mass_fraction_user{user}_{plane}"] = nanmean_col(df, f"mass_fraction_user{user}")

            row[f"RMSE_D32_vs_Fluent_{plane}"] = rmse_against_ref(
                df, "D32_um", ref.get(plane, {}).get("fluent_smd")
            )
            row[f"RMSE_D32_vs_Experiment_{plane}"] = rmse_against_ref(
                df, "D32_um", ref.get(plane, {}).get("exp_smd")
            )
            row[f"RMSE_Ux_vs_Fluent_{plane}"] = rmse_against_ref(
                df, "Ux_mean", ref.get(plane, {}).get("fluent_ux")
            )
            row[f"RMSE_Ux_vs_Experiment_{plane}"] = rmse_against_ref(
                df, "Ux_mean", ref.get(plane, {}).get("exp_ux")
            )

        rows.append(row)

    out_csv = out_dir / "Lambert_J20_kernel_error_summary.csv"
    pd.DataFrame(rows).to_csv(out_csv, index=False)
    print(f"Saved: {out_csv}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare Lambert J20 experimental/Lambert references with OpenFOAM DBM kernel cases."
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Root folder of Lambert_case_J20_kernelStudy. Default: inferred from script location or current directory.",
    )
    parser.add_argument(
        "--single-script",
        default=None,
        help="Path to postprocess_lambert_openfoam.py containing REF. Default: postProcessing_kernelComparison/postprocess_lambert_openfoam.py",
    )
    parser.add_argument(
        "--run-single",
        action="store_true",
        help="Before global comparison, run the single-case postprocess script for every kernel case.",
    )
    parser.add_argument("--dz", type=float, default=0.001)
    parser.add_argument("--min-events", type=int, default=100)
    parser.add_argument("--bins", type=int, default=30)
    parser.add_argument("--y-min", type=float, default=0.0)
    parser.add_argument("--y-max", type=float, default=0.015)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    script_path = Path(__file__).resolve()
    root, out_dir = infer_paths(script_path, args.root)

    print("Root folder:", root)
    print("Output folder:", out_dir)

    cases = DEFAULT_CASES

    if args.run_single:
        run_single_postprocessing(root, out_dir, cases.keys(), args)

    ref = load_reference_data(out_dir, args.single_script)

    make_combined_figure(root, out_dir, cases, ref)
    make_quantity_figures(root, out_dir, cases, ref)
    make_single_plane_figures(root, out_dir, cases, ref)
    write_summary(root, out_dir, cases, ref)

    print("\nCompleted.")
    print("Generated files are in:")
    print(out_dir)


if __name__ == "__main__":
    main()
